FROM centos:8
LABEL maintainer="tsmith@chef.io"

RUN dnf -y install \
    ca-certificates \
    cronie \
    curl \
    gnupg2 \
    initscripts \
    iptables \
    iputils \
    lsof \
    nc \
    net-tools \
    nmap \
    openssl \
    passwd \
    procps \
    strace \
    sudo \
    systemd-sysv \
    redhat-lsb-core \
    tcpdump \
    telnet \
    util-linux \
    vim-minimal \
    wget \
    which && \
    dnf upgrade -y && \
    dnf clean all

CMD [ "/usr/lib/systemd/systemd" ]
