name: ci

on:
  pull_request:

jobs:
  buildx-arm64-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-with-arm64:
          - 'almalinux-8'
          - 'almalinux-9'
          - 'amazonlinux-2'
          - 'amazonlinux-2022'
          - 'centos-7'
          - 'centos-8'
          - 'centos-stream-8'
          - 'centos-stream-9'
          - 'debian-9'
          - 'debian-10'
          - 'debian-11'
          - 'debian-12'
          - 'fedora-34'
          - 'fedora-35'
          - 'fedora-latest'
          - 'opensuse-leap-15'
          - 'opensuse-leap-15.3'
          - 'opensuse-leap-15.4'
          - 'oraclelinux-7'
          - 'oraclelinux-8'
          - 'rockylinux-8'
          - 'ubuntu-14.04'
          - 'ubuntu-16.04'
          - 'ubuntu-18.04'
          - 'ubuntu-20.04'
          - 'ubuntu-21.04'
          - 'ubuntu-21.10'
          - 'ubuntu-22.04'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build-date
        run: echo "::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        id: build-date
      - name: Short git sha
        run: echo "::set-output name=short::$(echo ${GITHUB_SHA} | cut -c1-8)"
        id: git-sha
      - name: Build arm64 and amd64
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          file: ./${{ matrix.os-with-arm64 }}/Dockerfile
          build-args: |
            BUILD_DATE=${{ steps.build-date.outputs.build_date}}
            VCS_REF=${{ steps.git-sha.outputs.short }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  buildx-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-without-arm64:
          - 'centos-6'
          - 'oraclelinux-6'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build-date
        run: echo "::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        id: build-date
      - name: Short git sha
        run: echo "::set-output name=short::$(echo ${GITHUB_SHA} | cut -c1-8)"
        id: git-sha
      - name: Build amd64 only
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          file: ./${{ matrix.os-without-arm64 }}/Dockerfile
          build-args: |
            BUILD_DATE=${{ steps.build-date.outputs.build_date}}
            VCS_REF=${{ steps.git-sha.outputs.short }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
